version: '3.1'

volumes:
  mongodb-data: {}

services:
  nuxt:
    build: ./nuxt
    command: yarn run dev
    volumes:
      - ./nuxt:/nuxt
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - "mongodb-data:/data/db"

